### ISSUE TITLE
Error while converting lstm graph

### ISSUE THREAD

**Issue by mrsabhar-Intel** [intel/neural-compressor#1]
Quantizing model which takes multiple input image based on time distribution. Is there way to skip layer if it is not supported?

2021-01-04 16:10:53 [INFO] Start to run model quantization...
| ************Mixed Precision Statistics************ |
| INT8 Conv2D: 30                                    |
| INT8 MaxPool: 4                                    |
| INT8 ConcatV2: 4                                   |
| Overall: INT8 100.00% (38/38) BF16 0.00% (0/38)    |
| ************************************************** |
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.0-py3.7.egg/lpot/adaptor/tf_utils/graph_converter.py", line 505, in quantize
    self._quantize_graph()
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.0-py3.7.egg/lpot/adaptor/tf_utils/graph_converter.py", line 577, in _quantize_graph
    self._tmp_graph_def = intel_quantizer.do_transform()
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.0-py3.7.egg/lpot/adaptor/tf_utils/quantize_graph/quantize_graph_for_intel_cpu.py", line 107, in do_transform
    self.input_graph = worker.apply_the_transform()
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.0-py3.7.egg/lpot/adaptor/tf_utils/quantize_graph/quantize_graph_conv.py", line 356, in apply_the_transform
    self.fusion_mapping[fusion_name](matched_node_name)
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.0-py3.7.egg/lpot/adaptor/tf_utils/quantize_graph/quantize_graph_conv.py", line 214, in apply_conv_biasadd_fusion
    matched_node.node.op, self.node_name_mapping[weight_name].node,
KeyError: 'conv_lst_m2d/while/split:3'
2021-01-04 16:10:55 [ERROR] Failed to quantize graph due to: 'conv_lst_m2d/while/split:3'
Traceback (most recent call last):
  File "inference_Sequential.py", line 272, in <module>
    q_model = quantizer('./save/tf_model.pb', q_dataloader = dataloader)
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.0-py3.7.egg/lpot/quantization.py", line 221, in __call__
    self.strategy.traverse()
  File "/usr/local/lib/python3.7/dist-packages/lpot-1.0-py3.7.egg/lpot/strategy/strategy.py", line 266, in traverse
    assert self.last_qmodel
AssertionError

**Comment by guomingz** [comment]
Hi @mrsabhar  thanks for reporting this issue.
We're working on that and the will deliver the solution for v1.2

**Comment by hshen14** [comment]
Preview feature is supported. Close this, and please re-open if you have some new requests. Thanks.
