### ISSUE TITLE
Unable to save resnet_quantization model

### ISSUE THREAD

**Issue by mattam301** [intel/neural-compressor#1275]
i was trying to run resnet_quantization in example folder and encountered this, anyone has any idea how to solve this:

this is the code:
from tqdm import tqdm
import time
from neural_compressor import quantization
from neural_compressor.config import PostTrainingQuantConfig

conf = PostTrainingQuantConfig(calibration_sampling_size=[50, 100], excluded_precisions = ['bf16'])

def eval_func(model):
    from neural_compressor.model import Model
    model = Model(model)
    ans = []
    total_cnt = 0
    total_hit = 0
    latency_list = []
    for idx, (batch_inputs, labels) in enumerate(tqdm(eval_dataloader)):
        feed_dict = dict(zip(model.input_tensor, [batch_inputs]))
        start = time.time()
        preds = model.sess.run(model.output_tensor, feed_dict)
        end = time.time()
        latency_list.append(end-start)
        ans = np.argmax(preds[0], axis=-1)
        labels += 1    # label shift
        total_cnt += len(labels)
        total_hit += np.sum(ans == labels)
    acc = total_hit / total_cnt
    latency = np.array(latency_list).mean() / eval_dataloader.batch_size
    return acc

q_model = quantization.fit("./resnet50_fp32_pretrained_model.pb", conf=conf, calib_dataloader=calib_dataloader, eval_func=eval_func)
q_model.save("resnet50_int8.pb")

2023-09-22 04:18:47 [ERROR] Unexpected exception UnsupportedOperation('fileno') happened during tuning.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/neural_compressor/quantization.py", line 223, in fit
    strategy.traverse()
  File "/usr/local/lib/python3.10/dist-packages/neural_compressor/strategy/auto.py", line 134, in traverse
    super().traverse()
  File "/usr/local/lib/python3.10/dist-packages/neural_compressor/strategy/strategy.py", line 503, in traverse
    q_model = self.adaptor.quantize(copy.deepcopy(tune_cfg), self.model, self.calib_dataloader, self.q_func)
  File "/usr/local/lib/python3.10/dist-packages/neural_compressor/utils/utility.py", line 301, in fi
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/neural_compressor/adaptor/tensorflow.py", line 700, in quantize
    ).convert()
  File "/usr/local/lib/python3.10/dist-packages/neural_compressor/adaptor/tf_utils/graph_converter.py", line 401, in convert
    model = self.quantize()
  File "/usr/local/lib/python3.10/dist-packages/neural_compressor/adaptor/tf_utils/graph_converter.py", line 555, in quantize
    with CaptureOutputToFile(tmp_dump_file):
  File "/usr/local/lib/python3.10/dist-packages/neural_compressor/utils/utility.py", line 448, in __init__
    self.orig_stream_fileno = stream.fileno()
io.UnsupportedOperation: fileno
2023-09-22 04:18:47 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-10-a190cf823091>](https://ocf6a0x8kl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20230920-060121_RC00_566908972#) in <cell line: 30>()
     28 
     29 q_model = quantization.fit("./resnet50_fp32_pretrained_model.pb", conf=conf, calib_dataloader=calib_dataloader, eval_func=eval_func)
---> 30 q_model.save("resnet50_int8.pb")

AttributeError: 'NoneType' object has no attribute 'save'

**Comment by lvliang-intel** [comment]
Hi @mattam301,

Thank you for bringing up this issue. Looks like you run the example code on Jupyter Notebook. The root cause of the problem lies in the way Jupyter Notebooks capture system input and output. However, Intel Neural Compressor requires access to the standard input and output for quantization calibration purposes. To address this issue, you will need to set up a Conda environment locally for testing, not on Jupyter Notebook.

**Comment by mattam301** [comment]
i am setting up locally using a Conda environment named neucom, but i cant even import quantization:
from neural_compressor import quantization
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/__init__.py", line 28, in <module>
    from .contrib import *
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/contrib/__init__.py", line 18, in <module>
    from .strategy import *
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/contrib/strategy/__init__.py", line 25, in <module>
    __import__(basename(f)[:-3], globals(), locals(), level=1)
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/contrib/strategy/tpe.py", line 26, in <module>
    from neural_compressor.strategy.strategy import TuneStrategy, strategy_registry
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/strategy/__init__.py", line 19, in <module>
    from .strategy import STRATEGIES
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/strategy/strategy.py", line 37, in <module>
    from ..adaptor import FRAMEWORKS
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/adaptor/__init__.py", line 26, in <module>
    __import__(basename(f)[:-3], globals(), locals(), level=1)
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/adaptor/pytorch.py", line 43, in <module>
    REDUCE_RANGE = False if CpuInfo().vnni else True
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/utils/utility.py", line 129, in _singleton
    instances[cls] = cls(*args, **kw)
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/utils/utility.py", line 252, in __init__
    self._sockets = self.get_number_of_sockets()
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/utils/utility.py", line 287, in get_number_of_sockets
    return int(line.decode("utf-8", errors="ignore").strip())
ValueError: invalid literal for int() with base 10: '/bin/sh: lscpu: command not found'

Is there any chance that this is because of my Apple-M1 chip?

**Comment by lvliang-intel** [comment]
Hi @mattam301,

`ValueError: invalid literal for int() with base 10: '/bin/sh: lscpu: command not found'`
'lscpu' is not supported on MacOS. Our test only covers Linux and Windows.

**Comment by chensuyue** [comment]
Yes, that's known issue, we will support MacOS in our next release.
