### ISSUE TITLE
Does it support Apple M1 CPU?

### ISSUE THREAD

**Issue by mattam301** [intel/neural-compressor#1278]
I am trying to set up it locally, but unable to import neural compressor since it raised this error:
>>> import neural_compressor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/__init__.py", line 28, in <module>
    from .contrib import *
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/contrib/__init__.py", line 18, in <module>
    from .strategy import *
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/contrib/strategy/__init__.py", line 25, in <module>
    __import__(basename(f)[:-3], globals(), locals(), level=1)
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/contrib/strategy/tpe.py", line 26, in <module>
    from neural_compressor.strategy.strategy import TuneStrategy, strategy_registry
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/strategy/__init__.py", line 19, in <module>
    from .strategy import STRATEGIES
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/strategy/strategy.py", line 35, in <module>
    from neural_compressor.adaptor.tensorflow import TensorFlowAdaptor
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/adaptor/__init__.py", line 26, in <module>
    __import__(basename(f)[:-3], globals(), locals(), level=1)
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/adaptor/pytorch.py", line 43, in <module>
    REDUCE_RANGE = False if CpuInfo().vnni else True
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/utils/utility.py", line 129, in _singleton
    instances[cls] = cls(*args, **kw)
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/utils/utility.py", line 252, in __init__
    self._sockets = self.get_number_of_sockets()
  File "/Users/tuanmai/miniconda3/envs/neucom/lib/python3.10/site-packages/neural_compressor/utils/utility.py", line 287, in get_number_of_sockets
    return int(line.decode("utf-8", errors="ignore").strip())
ValueError: invalid literal for int() with base 10: '/bin/sh: lscpu: command not found'

Is there anything to do related to my chip?

**Comment by chensuyue** [comment]
Yes, we haven't support MacOS yet. Our tests only cover Linux and Windows.

**Comment by chensuyue** [comment]
We plan to support MacOS in our next release.
