### ISSUE TITLE
RuntimeError in quantizing Segment Anything Model - Float QUInt8

### ISSUE THREAD

**Issue by cfgfung** [intel/neural-compressor#1316]
Encounter the following error when applying PTQ on the Segment Anything Model:

```
2023-09-19 17:00:33 [WARNING] The dataloader didn't include label, will try input without label!
2023-09-19 17:00:33 [ERROR] Unexpected exception AssertionError('The dataloader must include label to measure the metric!') happened during tuning.
Traceback (most recent call last):
File "/home/users/users/sam_env/lib/python3.9/site-packages/neural_compressor/adaptor/pytorch.py", line 939, in eval_func
output = pytorch_forward_wrapper(model, input, device=self.device, conf=conf)
File "/home/users/users/sam_env/lib/python3.9/site-packages/neural_compressor/adaptor/pytorch.py", line 85, in pytorch_forward_wrapper
output = model(**input)
File "/home/users/users/sam_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/global/panfs01/users/users/segment-anything-inc/segment-anything/ptq_sam.py", line 208, in forward
sparse_embeddings, dense_embeddings = self.prompt_encoder(
File "/home/users/users/sam_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/global/panfs01/users/users/segment-anything-inc/segment-anything/segment_anything/modeling/prompt_encoder.py", line 158, in forward
box_embeddings = self._embed_boxes(boxes)
File "/global/panfs01/users/users/segment-anything-inc/segment-anything/segment_anything/modeling/prompt_encoder.py", line 98, in _embed_boxes
corner_embedding[:, 0, :] += self.point_embeddings[2].weight
RuntimeError: promoteTypes with quantized numbers is not handled yet; figure out what the correct rules should be, offending types: Float QUInt8
```

**Comment by cfgfung** [comment]
With the help of the INC developer, a solution is found:

We can skip quantizing the mentioned embeddings by adding an op_type_dict in the config.
```
    op_type_dict={
        'Embedding':

{             'weight': \{'dtype': 'fp32'}
,
            'activation': {'dtype': 'fp32'},
        }
    }
    config = PostTrainingQuantConfig(op_type_dict=op_type_dict)
```
