### ISSUE TITLE
KeyError: '/post'

### ISSUE THREAD

**Issue by lshqqytiger** [intel/neural-compressor#1506]
I'm trying to quantize Stable Diffusion model using [IncDynamicQuantization](https://microsoft.github.io/Olive/api/passes.html#incdynamicquantization).

I was able to quantize text encoder, unet and vae encoder, but I met `KeyError: '/post'` while quantizing vae decoder.
The source model is ONNX format.

Olive config:
```
    "quantization": {
      "type": "IncDynamicQuantization",
      "disable_search": true,
      "config": {
        "save_as_external_data": false,
        "all_tensors_to_one_file": true
      }
    }
```

Traceback:
```
Traceback (most recent call last):
  File "D:\miniconda3\envs\olivedml\lib\site-packages\neural_compressor\quantization.py", line 234, in fit
    strategy.traverse()
  File "D:\miniconda3\envs\olivedml\lib\site-packages\neural_compressor\strategy\auto.py", line 140, in traverse
    super().traverse()
  File "D:\miniconda3\envs\olivedml\lib\site-packages\neural_compressor\strategy\strategy.py", line 504, in traverse
    q_model = self.adaptor.quantize(copy.deepcopy(tune_cfg), self.model, self.calib_dataloader, self.q_func)
  File "D:\miniconda3\envs\olivedml\lib\site-packages\neural_compressor\utils\utility.py", line 304, in fi
    res = func(*args, **kwargs)
  File "D:\miniconda3\envs\olivedml\lib\site-packages\neural_compressor\adaptor\onnxrt.py", line 431, in quantize
    quantizer.quantize_model()
  File "D:\miniconda3\envs\olivedml\lib\site-packages\neural_compressor\adaptor\ox_utils\quantizer.py", line 181, in quantize_model
    self.insert_qdq()
  File "D:\miniconda3\envs\olivedml\lib\site-packages\neural_compressor\adaptor\ox_utils\quantizer.py", line 299, in insert_qdq
    op_quantizer.quantize()
  File "D:\miniconda3\envs\olivedml\lib\site-packages\neural_compressor\adaptor\ox_utils\operators\conv.py", line 49, in quantize
    self.quantizer.quantize_inputs(node, [0])
  File "D:\miniconda3\envs\olivedml\lib\site-packages\neural_compressor\adaptor\ox_utils\quantizer.py", line 628, in quantize_inputs
    if self.config[node.name.split("_quant")[0]]["activation"]["quant_mode"] != "dynamic":
KeyError: '/post'
```

Full log:
[log.txt](https://github.com/intel/neural-compressor/files/13792889/log.txt)

Versions:
Python 3.10.12
onnxruntime 1.16.3
olive-ai 0.4.0
neural-compressor 2.4

**Comment by yiliu30** [comment]
Hi @lshqqytiger , thanks for bringing up this issue. Can you share the code snippet or the model name/link? This will help us to reproduce the issue.

**Comment by lshqqytiger** [comment]
Example python project: https://github.com/lshqqytiger/inc-vae-decoder-snippet
This error is common across all Stable Diffusion models.

**Comment by yiliu30** [comment]
Thanks for the details, I reproduced it and fixed it on the [branch](https://github.com/intel/neural-compressor/tree/ly/fix_ort). Feel free to test it at your convenience.

**Comment by lshqqytiger** [comment]
I can confirm #1512 fixes this issue. Thank you for quick fix.
