### ISSUE TITLE
[ONNX] AttributeError: 'tuple' object has no attribute 'replace'

### ISSUE THREAD

**Issue by peiwenhuang27** [intel/neural-compressor#23]
LPOT Version: 1.5.1
ONNX Version: 1.7
ONNXRuntime Version: 1.6.0
Environment: Google Colab

Configuration:
```
quantization:
  calibration:
    sampling_size: 500
  model_wise:
    weight:
      granularity: per_channel
      scheme: sym
      algorithm: minmax
    activation:
      granularity: per_tensor
      scheme: sym
      algorithm: minmax

evaluation:
  accuracy:
    metric:
      MSE: {}  
  performance:                               
    warmup: 30
    iteration: 300

tuning:
  objective: performance
  random_seed: 9527
  strategy:
    name: mse
  accuracy_criterion:
    higher_is_better: False
    relative: 0.8
  exit_policy:
    performance_only: False
    max_trials: 20
    timeout: 100000
```
When quantizing my ONNX model, at the first tune it seems fine and outputs the accuracy and latency, but in `tune 2` the following error happens:

```
Traceback (most recent call last):
  File "main.py", line 154, in <module>
    q_model = quantize()
  File "/usr/local/lib/python3.7/dist-packages/lpot/experimental/quantization.py", line 178, in __call__
    self.strategy.traverse()
  File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/strategy.py", line 296, in traverse
    for tune_cfg in self.next_tune_cfg():
  File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/mse.py", line 145, in next_tune_cfg
    self.model, self.calib_dataloader, op_lists, [1])
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/onnxrt.py", line 200, in inspect_tensor
    weight=(inspect_type!='activation'))
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/ox_utils/onnxrt_mid.py", line 417, in dump_tensor
    self.white_nodes = [node.replace('_quant', '') for node in self.white_nodes]
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/ox_utils/onnxrt_mid.py", line 417, in <listcomp>
    self.white_nodes = [node.replace('_quant', '') for node in self.white_nodes]
AttributeError: 'tuple' object has no attribute 'replace'
```

**Comment by peiwenhuang27** [comment]
For the object `node` that is considered a tuple instead of string, I printed it out and it looks like this:
`('StatefulPartitionedCall/model/1/Conv2D', 'Conv')`, which is a tuple consisting of two strings. Which one should I use in this place?

**Comment by mengniwang95** [comment]
@peiwenhuang27 thanks for raising this issue, you should use the first one. I will fix this bug and provide a patch file.

**Comment by peiwenhuang27** [comment]
Thanks! I'll wait for the patch file to try again later.

**Comment by mengniwang95** [comment]
[inspect.txt](https://github.com/intel/lpot/files/6898367/inspect.txt)

@peiwenhuang27 this patch is generated with internal previous commit. So the line number is different from the public one

**Comment by peiwenhuang27** [comment]
I added the lines to `onnxrt.py` as in the patch file, then this occurs:
```
Traceback (most recent call last):
  File "main.py", line 154, in <module>
    q_model = quantize()
  File "/usr/local/lib/python3.7/dist-packages/lpot/experimental/quantization.py", line 178, in __call__
    self.strategy.traverse()
  File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/strategy.py", line 296, in traverse
    for tune_cfg in self.next_tune_cfg():
  File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/mse.py", line 145, in next_tune_cfg
    self.model, self.calib_dataloader, op_lists, [1])
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/onnxrt.py", line 195, in inspect_tensor
    if len(op_list) == 0 or isinstance(op_list[0], str):
TypeError: 'odict_keys' object is not subscriptable

```

**Comment by mengniwang95** [comment]
[inspect.txt](https://github.com/intel/lpot/files/6899105/inspect.txt)

@peiwenhuang27 Sorry for my unprofessional, pls try this new patch again.

**Comment by peiwenhuang27** [comment]
No worries! I really do appreciate all you guys' efforts in this great tool 😊

I tried using the new patch, and then this happens:
```
2021-07-29 09:12:40 [INFO] |*******Mixed Precision Statistics*******|
2021-07-29 09:12:40 [INFO] +----------------------+---------+-------+
2021-07-29 09:12:40 [INFO] |       Op Type        |  Total  |  INT8 |
2021-07-29 09:12:40 [INFO] +----------------------+---------+-------+
2021-07-29 09:12:40 [INFO] |         Conv         |    8    |   8   |
2021-07-29 09:12:40 [INFO] |        MatMul        |    6    |   6   |
2021-07-29 09:12:40 [INFO] |         Mul          |    2    |   2   |
2021-07-29 09:12:40 [INFO] |      LeakyRelu       |    8    |   8   |
2021-07-29 09:12:40 [INFO] |       Sigmoid        |    3    |   3   |
2021-07-29 09:12:40 [INFO] |         Add          |    5    |   5   |
2021-07-29 09:12:40 [INFO] |    QuantizeLinear    |    13   |   13  |
2021-07-29 09:12:40 [INFO] |   DequantizeLinear   |    13   |   13  |
2021-07-29 09:12:40 [INFO] +----------------------+---------+-------+
2021-07-29 09:12:40 [INFO] Pass quantize model elapsed time: 61369.01 ms
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearAdd. No schema registered for this operator.
Warning: Unsupported operator QLinearSigmoid. No schema registered for this operator.
Warning: Unsupported operator QLinearMul. No schema registered for this operator.
Warning: Unsupported operator QLinearAdd. No schema registered for this operator.
Warning: Unsupported operator QLinearAdd. No schema registered for this operator.
Warning: Unsupported operator QLinearSigmoid. No schema registered for this operator.
Warning: Unsupported operator QLinearMul. No schema registered for this operator.
Warning: Unsupported operator QLinearAdd. No schema registered for this operator.
Warning: Unsupported operator QLinearAdd. No schema registered for this operator.
Warning: Unsupported operator QLinearSigmoid. No schema registered for this operator.
2021-07-29 09:12:40.408709436 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/42/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.409391842 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_3/Sigmoid:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.409780086 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/multiply_1/mul:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.409946411 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_5/Sigmoid:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.410217000 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/51/Conv2D:0_quantized_output' source:{64,8,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.410542583 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense/BiasAdd:0_quantized_output' source:{64,60,600} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.410713608 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/1/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.410876688 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/52/LeakyRelu:0_quantized_output' source:{64,8,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.411039542 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_4/Tensordot/MatMul:0_quantized_output' source:{3840,400} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.411190409 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/32/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.411362426 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense/Tensordot/MatMul:0_quantized_output' source:{3840,600} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.411534705 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/1/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.411695712 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/2/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.411854370 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_2/Tensordot/MatMul:0_quantized_output' source:{3840,600} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.412014974 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_3/BiasAdd:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.412173777 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/42/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.412339732 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_4/BiasAdd:0_quantized_output' source:{64,60,400} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.412607135 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_1/Sigmoid:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.412768970 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/32/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.412927818 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_1/Tensordot/MatMul:0_quantized_output' source:{3840,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.413089054 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/41/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.413253272 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_3/Tensordot/MatMul:0_quantized_output' source:{3840,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.413412338 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/41/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.413581824 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/52/Conv2D:0_quantized_output' source:{64,8,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.413741855 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/2/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.413900882 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_5/BiasAdd:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.414062395 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_1/BiasAdd:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.414226413 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/51/LeakyRelu:0_quantized_output' source:{64,8,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.414386359 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/31/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.414598588 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/31/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.414767790 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/multiply/mul:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:40.414934893 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_5/Tensordot/MatMul:0_quantized_output' source:{3840,257} target:{}. Falling back to lenient merge.
2021-07-29 09:12:50 [ERROR] Unexpected exception KeyError('S') happened during turing!
2021-07-29 09:12:51 [INFO] Specified timeout or max trials is reached! Found a quantized model which meet accuracy goal. Exit...

```

**Comment by mengniwang95** [comment]
@peiwenhuang27 According to your error info, the model has been quantized and begin to evaluate. The error info is insufficient so I can not confirm where it crashed.
Could you make some code changes and run quantization again, then paste the error info?

Code change:
https://github.com/intel/lpot/blob/f4c4ca35d99de940ad90ea24e1dc80e18fda8dea/lpot/experimental/quantization.py#L176
Comment code from line 176 to 183, adjust the indent from line 184 to 194, add 'self.strategy.traverse()' to line 175

Thanks
Mengni

**Comment by peiwenhuang27** [comment]
After I changed the code, the error info still remains the same though.
I changed the code in `quantization.py` as:
```
        self.strategy.traverse()
        # try:
        #     with time_limit(self.conf.usr_cfg.tuning.exit_policy.timeout):
        #         self.strategy.traverse()
        # except KeyboardInterrupt:
        #     pass
        # except Exception as e:
        #     logger.error("Unexpected exception {} happened during turing!".format(repr(e)))
        # finally:
        if self.strategy.best_qmodel:
            logger.info(
                "Specified timeout or max trials is reached! "
                "Found a quantized model which meet accuracy goal. Exit...")
            self.strategy.deploy_config()
        else:
            logger.error(
                "Specified timeout or max trials is reached! "
                "Not found any quantized model which meet accuracy goal. Exit...")

            return self.strategy.best_qmodel
```
The warning lines look the same:
```
2021-07-30 03:16:38 [INFO] Pass quantize model elapsed time: 239254.73 ms
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearLeakyRelu. No schema registered for this operator.
Warning: Unsupported operator QLinearAdd. No schema registered for this operator.
Warning: Unsupported operator QLinearSigmoid. No schema registered for this operator.
Warning: Unsupported operator QLinearMul. No schema registered for this operator.
Warning: Unsupported operator QLinearAdd. No schema registered for this operator.
Warning: Unsupported operator QLinearAdd. No schema registered for this operator.
Warning: Unsupported operator QLinearSigmoid. No schema registered for this operator.
Warning: Unsupported operator QLinearMul. No schema registered for this operator.
Warning: Unsupported operator QLinearAdd. No schema registered for this operator.
Warning: Unsupported operator QLinearAdd. No schema registered for this operator.
Warning: Unsupported operator QLinearSigmoid. No schema registered for this operator.
2021-07-30 03:16:38.658788179 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/42/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.661616148 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_1/Sigmoid:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.661738301 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/52/Conv2D:0_quantized_output' source:{64,8,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.661968131 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_3/Sigmoid:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662054454 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/41/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662131834 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/51/Conv2D:0_quantized_output' source:{64,8,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662211268 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/41/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662384399 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_5/BiasAdd:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662472933 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/multiply_1/mul:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662562698 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_1/Tensordot/MatMul:0_quantized_output' source:{3840,257} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662640371 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/1/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662722585 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/32/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662798685 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/51/LeakyRelu:0_quantized_output' source:{64,8,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662872899 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense/Tensordot/MatMul:0_quantized_output' source:{3840,600} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.662947928 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/31/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663021420 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_4/Tensordot/MatMul:0_quantized_output' source:{3840,400} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663096368 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_3/BiasAdd:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663170776 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/32/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663245524 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/42/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663319850 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/1/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663394028 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_3/Tensordot/MatMul:0_quantized_output' source:{3840,257} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663468315 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_2/Tensordot/MatMul:0_quantized_output' source:{3840,600} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663554115 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/52/LeakyRelu:0_quantized_output' source:{64,8,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663629565 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/2/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663708881 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_4/BiasAdd:0_quantized_output' source:{64,60,400} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663824720 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/2/LeakyRelu:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663908194 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_1/BiasAdd:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.663982914 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_5/Tensordot/MatMul:0_quantized_output' source:{3840,257} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.664058194 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/31/Conv2D:0_quantized_output' source:{64,64,257,60} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.664131965 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense/BiasAdd:0_quantized_output' source:{64,60,600} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.664207239 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/multiply/mul:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
2021-07-30 03:16:38.664281131 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/model/dense_5/Sigmoid:0_quantized_output' source:{64,60,257} target:{}. Falling back to lenient merge.
run_tuning.sh: line 31:   918 Killed                  python main.py --model_path ${input_model} --output_model ${output_model} --config ${config} --tune
/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown
  len(cache))
```
