### ISSUE TITLE
[Tensorflow] Fail to quantize graph due to list index (0) out of range.

### ISSUE THREAD

**Issue by peiwenhuang27** [intel/neural-compressor#26]
Environment: Google Colab
LPOT: 1.6
Tensorflow: official 2.6.0
> Please find my model [here](https://drive.google.com/drive/folders/1z3qcOYyhGwjRrcA3QVZAVwZA01vO1nEK?usp=sharing)

I am trying to quantize a Keras model, but in the middle of quantization prints the following error:
```
...
2021-08-30 01:27:42 [INFO] Unknown fusion pattern Conv2DRelu.
2021-08-30 01:27:42 [INFO] Unknown fusion pattern Conv2DRelu.
2021-08-30 01:27:42 [INFO] Unknown fusion pattern Conv2DRelu.
2021-08-30 01:27:43 [INFO] Unknown fusion pattern Conv2DRelu.
2021-08-30 01:27:44 [INFO] Pass Quantization elapsed time: 2318.58 ms
2021-08-30 01:28:14 [INFO] Pass QuantizedRNNConverter elapsed time: 55.02 ms
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/tf_utils/graph_converter.py", line 572, in quantize
    self._fuse_requantize_with_fused_quantized_node()
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/tf_utils/graph_converter.py", line 705, in _fuse_requantize_with_fused_quantized_node
    self._tmp_graph_def).do_transformation()
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/tf_utils/graph_rewriter/int8/fuse_matmul_requantize.py", line 106, in do_transformation
    min_input_value = (min_input_node.attr['value'].tensor.float_val)[0]
IndexError: list index (0) out of range
2021-08-30 01:28:14 [ERROR] Fail to quantize graph due to list index (0) out of range.
2021-08-30 01:28:14 [ERROR] Unexpected exception AttributeError("'NoneType' object has no attribute 'graph_def'") happened during tuning.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/lpot/experimental/quantization.py", line 140, in execute
    self.strategy.traverse()
  File "/usr/local/lib/python3.7/dist-packages/lpot/strategy/strategy.py", line 329, in traverse
    tune_cfg, self.model, self.calib_dataloader, self.q_func)
  File "/usr/local/lib/python3.7/dist-packages/lpot/utils/utility.py", line 201, in fi
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/tensorflow.py", line 350, in quantize
    data_loader=data_loader).convert()
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/tf_utils/graph_converter.py", line 249, in convert
    post_cse_graph_def = PostCseOptimizer(model.graph_def).do_transformation()
AttributeError: 'NoneType' object has no attribute 'graph_def'
2021-08-30 01:28:14 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    evaluate_opt_graph.run()
  File "main.py", line 104, in run
    q_model.save(self.args.output_graph) 
AttributeError: 'NoneType' object has no attribute 'save'
```

Inside `lpot/adaptor/tf_utils/graph_rewriter/int8/fuse_matmul_requantize.py`, I printed out the node that caused the error:

```
### max_filter_node ###
name: "model/dense_4/Tensordot/ReadVariableOp_max"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
      }
      float_val: 17.38440704345703
    }
  }
}

### max_input_node ###
name: "model/dense_4/Tensordot/MatMul_eightbit_max_model/dense_4/Tensordot/Reshape/frozen_max_only"
op: "Const"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "value"
  value {
    tensor {
      dtype: DT_FLOAT
      tensor_shape {
      }
      float_val: 49.27424240112305
    }
  }
}

### min_input_node ###
name: "model/dense_4/Tensordot/MatMul_eightbit_min_model/dense_4/Tensordot/Reshape"
op: "Min"
input: "model/dense_4/Tensordot/MatMul_eightbit_reshape_model/dense_4/Tensordot/Reshape"
input: "model/dense_4/Tensordot/MatMul_eightbit_reduction_dims"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "Tidx"
  value {
    type: DT_INT32
  }
}
attr {
  key: "keep_dims"
  value {
    b: false
  }
}




Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/tf_utils/graph_converter.py", line 572, in quantize
    self._fuse_requantize_with_fused_quantized_node()
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/tf_utils/graph_converter.py", line 705, in _fuse_requantize_with_fused_quantized_node
    self._tmp_graph_def).do_transformation()
  File "/usr/local/lib/python3.7/dist-packages/lpot/adaptor/tf_utils/graph_rewriter/int8/fuse_matmul_requantize.py", line 114, in do_transformation
    min_input_value = (min_input_node.attr['value'].tensor.float_val)[0]
IndexError: list index (0) out of range
```

Looks like it is trying to quantize a reshape node, which has no `float_val` attribute.

**Comment by guomingz** [comment]
The model link is invalid. Please check.
what's the tf version ?

**Comment by peiwenhuang27** [comment]
I have fixed the model link, please check again, thanks!
As for Tensorflow version, it is Official 2.6.0.

**Comment by preethivenkatesh** [comment]
hi @guomingz is this issue fixed?

**Comment by ftian1** [comment]
let's close it at first and reopen if Peiwen still care about this issue
