### ISSUE TITLE
[Stock Tensorflow ResNet50_v1_5] calibration step has an error

### ISSUE THREAD

**Issue by sidkashyap-at-Intel** [intel/neural-compressor#29]
I followed the steps mentioned in the examples README.md to reproduce the resnet50_v1_5 results, but the calibration step fails to proceed ahead.

Can you kindly document the requirements for the calibration tf_records? The doc says it is optional in resnet50_v1_5.yaml, but it is not.  We cannot remove any of the options there. I am providing a few validation tf_records for calibration and have set the number of samples to be 100. 

```

bash run_tuning.sh --config=resnet50_v1_5.yaml  --input_model=./resnet50_v1.pb --output_model=./lpot_resnet50_v15.pb
+ main --config=resnet50_v1_5.yaml --input_model=./resnet50_v1.pb --output_model=./lpot_resnet50_v15.pb
+ init_params --config=resnet50_v1_5.yaml --input_model=./resnet50_v1.pb --output_model=./lpot_resnet50_v15.pb
+ for var in "$@"
+ case $var in
++ echo --config=resnet50_v1_5.yaml
++ cut -f2 -d=
+ config=resnet50_v1_5.yaml
+ for var in "$@"
+ case $var in
++ echo --input_model=./resnet50_v1.pb
++ cut -f2 -d=
+ input_model=./resnet50_v1.pb
+ for var in "$@"
+ case $var in
++ echo --output_model=./lpot_resnet50_v15.pb
++ cut -f2 -d=
+ output_model=./lpot_resnet50_v15.pb
+ run_tuning
+ python main.py --input-graph ./resnet50_v1.pb --output-graph ./lpot_resnet50_v15.pb --config resnet50_v1_5.yaml --tune
2021-09-23 19:51:46 [WARNING] Input tensor names should not be empty.
2021-09-23 19:51:46.650656: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-09-23 19:51:46.716141: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2021-09-23 19:51:47 [WARNING] Found possible input node names: ['input_tensor'], output node names: ['ArgMax', 'softmax_tensor'].
2021-09-23 19:51:48 [INFO] ConvertLayoutOptimizer elapsed time: 0.8 ms
2021-09-23 19:51:48.890494: I tensorflow/core/grappler/devices.cc:78] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2021-09-23 19:51:48.890959: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2021-09-23 19:51:48.914173: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2500000000 Hz
2021-09-23 19:51:49.375314: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:928] Optimization results for grappler item: graph_to_optimize
  model_pruner: Graph size after: 460 nodes (-278), 475 edges (-277), time = 103.298ms.
  shape_optimizer: shape_optimizer did nothing. time = 0.647ms.
  dependency_optimizer: Graph size after: 460 nodes (0), 475 edges (0), time = 24.819ms.
  debug_stripper: debug_stripper did nothing. time = 0.501ms.
  loop_optimizer: Graph size after: 460 nodes (0), 475 edges (0), time = 23.821ms.
  model_pruner: Graph size after: 460 nodes (0), 475 edges (0), time = 24.285ms.
  shape_optimizer: shape_optimizer did nothing. time = 0.462ms.
  dependency_optimizer: Graph size after: 460 nodes (0), 475 edges (0), time = 25.048ms.
  debug_stripper: debug_stripper did nothing. time = 0.608ms.

2021-09-23 19:51:49 [INFO] Pass GrapplerOptimizer elapsed time: 1042.24 ms
2021-09-23 19:51:49 [INFO] Pass RemoveTrainingNodesOptimizer elapsed time: 10.31 ms
2021-09-23 19:51:49 [INFO] Pass SplitSharedInputOptimizer elapsed time: 4.2 ms
2021-09-23 19:51:49 [INFO] Pass GraphFoldConstantOptimizer elapsed time: 3.15 ms
2021-09-23 19:51:49 [INFO] Pass FuseColumnWiseMulOptimizer elapsed time: 5.37 ms
2021-09-23 19:51:49 [INFO] Pass StripUnusedNodesOptimizer elapsed time: 14.49 ms
2021-09-23 19:51:49 [INFO] Pass GraphCseOptimizer elapsed time: 4.5 ms
2021-09-23 19:51:49 [INFO] Pass FoldBatchNormNodesOptimizer elapsed time: 352.35 ms
2021-09-23 19:51:49 [INFO] Pass UpdateEnterOptimizer elapsed time: 1.52 ms
2021-09-23 19:51:49 [INFO] Pass ConvertLeakyReluOptimizer elapsed time: 2.75 ms
2021-09-23 19:51:49 [INFO] Pass InjectDummyBiasAddOptimizer elapsed time: 2.79 ms
2021-09-23 19:51:49 [INFO] Pass ConvertAddToBiasAddOptimizer elapsed time: 2.78 ms
2021-09-23 19:51:49 [INFO] Pass FuseTransposeReshapeOptimizer elapsed time: 3.03 ms
2021-09-23 19:51:49 [INFO] Pass FuseConvWithMathOptimizer elapsed time: 2.96 ms
2021-09-23 19:51:50 [INFO] Pass Pre Optimization elapsed time: 2207.32 ms
2021-09-23 19:51:50 [INFO] Get FP32 model baseline.
2021-09-23 19:51:51 [INFO] Start to evaluate the TensorFlow model.
2021-09-23 19:51:51.116307: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-09-23 19:51:51.188329: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-09-23 19:51:51 [WARNING] Sample num during evaluation is 0.
2021-09-23 19:51:51 [INFO] Save tuning history to /mnt/storage/snkashya/BDL_lpot/neural-compressor/examples/tensorflow/image_recognition/lpot_workspace/2021-09-23_19-51-46/./history.snapshot.
2021-09-23 19:51:51 [INFO] FP32 baseline is: [accuracy: 0.0000, duration (seconds): 0.6577]
2021-09-23 19:51:52 [WARNING] Found possible input node names: ['input_tensor'], output node names: ['softmax_tensor'].
2021-09-23 19:51:52 [WARNING] Found possible input node names: ['input_tensor'], output node names: ['softmax_tensor'].
2021-09-23 19:51:54.882834: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2021-09-23 19:51:55 [INFO] Pass Quantization elapsed time: 1038.32 ms
Traceback (most recent call last):
  File "/home/snkashya/.conda/envs/lpot/lib/python3.7/site-packages/lpot/adaptor/tf_utils/graph_converter.py", line 561, in quantize
    self._calibration_data = Helper.gen_valid_sampling_log(tmp_dump_file)
  File "/home/snkashya/.conda/envs/lpot/lib/python3.7/site-packages/lpot/adaptor/tf_utils/graph_rewriter/graph_util.py", line 860, in gen_valid_sampling_log
    first_line = valid_data[0].rsplit(':')[0]
IndexError: list index out of range


```

**Comment by guomingz** [comment]
Would u please share us the yaml configuraton file, original fp32 pb and dataset if possible?

btw, what's the default metric of your model? 
i noticed that the evaluation on fp32 got below result. The accuracy is zero which doesn't looks good.
2021-09-23 19:51:51 [INFO] FP32 baseline is: [accuracy: 0.0000, duration (seconds): 0.6577]

**Comment by chensuyue** [comment]
Close first due to no response, pls reopen if you still have the same issue.
