### ISSUE TITLE
List out dependencies that are required to use neural-compressor

### ISSUE THREAD

**Issue by dmsuehir** [intel/neural-compressor#31]
When running `pip install neural-compressor`, I ran into the following error:
```
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
```
Through trial and error and googling the error, I found that I need to first install `build-essential` and `python3-dev`. After that, the pip install of neural compressor was successful, but something seems like it's still not right, because I get the following error when trying to do the imports from the [pruning doc](https://github.com/intel/neural-compressor/blob/master/docs/pruning.md#launcher-code).
```
>>> from neural_compressor.experimental import Pruning, common
2021-10-06 21:52:52 [INFO] generated new fontManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/__init__.py", line 18, in <module>
    from .quantization import Quantization
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/quantization.py", line 20, in <module>
    from .data import DATALOADERS, DATASETS
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/data/__init__.py", line 19, in <module>
    from .dataloaders import DataLoader
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/data/dataloaders/__init__.py", line 18, in <module>
    from .dataloader import DataLoader
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/data/dataloaders/dataloader.py", line 18, in <module>
    from neural_compressor.experimental.data.dataloaders import DATALOADERS
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/experimental/__init__.py", line 18, in <module>
    from .component import Component
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/experimental/component.py", line 17, in <module>
    from ..conf.config import Conf
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/conf/config.py", line 21, in <module>
    from ..strategy import STRATEGIES
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/strategy/__init__.py", line 18, in <module>
    from .strategy import STRATEGIES
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/strategy/strategy.py", line 30, in <module>
    from ..utils.create_obj_from_config import create_eval_func, create_train_func
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/utils/create_obj_from_config.py", line 19, in <module>
    from neural_compressor.experimental.data import DATASETS, TRANSFORMS, FILTERS, DATALOADERS
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/experimental/data/__init__.py", line 20, in <module>
    from .transforms import TRANSFORMS, BaseTransform, transform_registry
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/experimental/data/transforms/__init__.py", line 18, in <module>
    from .transform import TRANSFORMS, BaseTransform, transform_registry
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/experimental/data/transforms/transform.py", line 316, in <module>
    'nearest': cv2.INTER_NEAREST,
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/utils/utility.py", line 72, in __getattr__
    top_level_module = __import__(self.module_name)
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```
Can you list out all the dependencies that are required to install and run the neural compressor? I'm running this inside the `intel/intel-optimized-tensorflow:2.5.0-jupyter` container.

**Comment by dmsuehir** [comment]
Is it `build-essential`, `python3-dev`, and `python3-opencv` that are needed? Just `python3-opencv` alone didn't work for me.

**Comment by ftian1** [comment]
build-essentail is needed. it will provide gcc and pycoco will rely on it to dynamically generate cython object during installation.
