### ISSUE TITLE
Quantization AssertionError "inputs len must equal with input_tensor"

### ISSUE THREAD

**Issue by dmsuehir** [intel/neural-compressor#34]
I'm following the TensorFlow [BERT MRPC example](https://github.com/intel/neural-compressor/blob/master/examples/tensorflow/nlp/bert_base_mrpc/run_classifier.py) to run the neural compressor with a saved model that I exported after [fine tuning BERT from the Intel Model Zoo](https://github.com/IntelAI/models/tree/master/benchmarks/language_modeling/tensorflow/bert_large/training/fp32) using the IMDB movie review sentiment analysis dataset. The training task for this was "cola" instead of "mrpc", but I still used [run_classifier.py](https://github.com/IntelAI/models/blob/master/models/language_modeling/tensorflow/bert_large/training/fp32/run_classifier.py) to train the model.  
I used the same `Dataset` class definition and `collate_fn` from the example and my yaml has:
```
model:
  name: bert
  framework: tensorflow
  inputs: input_file, batch_size
  outputs: Cast_147:0, loss/Mean:0, loss/Neg:0, loss/Cast:0
```

My python code looks like this:
```
from neural_compressor.metric import METRICS
class Accuracy(object):
    def __init__(self):
        self.metric = METRICS('tensorflow')['Accuracy']()
          
    # it's ugly that the label is in the iterator
    def update(self, preds, label):
        logits, labels = preds
        self.metric.update(logits, labels)

    def reset(self):
        self.metric.reset()

    def result(self):
        return self.metric.result()

# Using run_classifier from the Intel model zoo
from run_classifier import file_based_input_fn_builder

eval_file = os.path.join(output_dir, "eval.tf_record")
estimator_input_fn = file_based_input_fn_builder(
          input_file=eval_file,
          seq_length=max_seq_length,
          is_training=False,
          drop_remainder=False)

quantizer.model = common.Model(os.path.join(output_dir, "frozen"), input_fn=estimator_input_fn)
quantizer.calib_dataloader = common.DataLoader(dataset, collate_fn=collate_fn)
quantizer.eval_dataloader = common.DataLoader(dataset, collate_fn=collate_fn)

quantizer.metric = common.Metric(metric_cls=Accuracy, name="bert_metric")
q_model = quantizer()
```

This is failing with the following error:
```
2021-10-11 20:32:11 [INFO] Start to evaluate the TensorFlow model.
2021-10-11 20:32:11 [ERROR] Unexpected exception AssertionError('inputs len must equal with input_tensor') happened during tuning.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/experimental/quantization.py", line 151, in execute
    self.strategy.traverse()
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/strategy/strategy.py", line 307, in traverse
    self.baseline = self._evaluate(self.model)
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/strategy/strategy.py", line 446, in _evaluate
    val = self.objective.evaluate(eval_func, model)
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/objective.py", line 213, in evaluate
    acc = eval_func(model)
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/utils/create_obj_from_config.py", line 132, in eval_func
    return adaptor.evaluate(model, dataloader, postprocess,
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/adaptor/tensorflow.py", line 291, in evaluate
    assert len(input_tensor) == len(inputs), \
AssertionError: inputs len must equal with input_tensor
```

The input_tensor for my model looks like this so I'm assuming that length is 4. What is other `inputs` that's being checked in the error above that has a different length than the input tensor?
```
[<tf.Tensor 'input_mask:0' shape=(None, 128) dtype=int32>,
 <tf.Tensor 'input_ids:0' shape=(None, 128) dtype=int32>,
 <tf.Tensor 'label_ids:0' shape=(None,) dtype=int32>,
 <tf.Tensor 'segment_ids:0' shape=(None, 128) dtype=int32>]
```

Any suggestions on how to resolve this issue?

**Comment by dmsuehir** [comment]
I think I figured out the error with the inputs. I think it might have had to do with the fact that I'm starting from a saved_model.pb which has inputs different than the example. I ended up using a Datasets class more similar the TFBERTDataSets class from [examples/engine/nlp/bert_base_mrpc/utils.py](https://github.com/intel/neural-compressor/blob/master/examples/engine/nlp/bert_base_mrpc/utils.py#L22).

Now, my output looks like this:
```
2021-10-15 21:01:44 [INFO] Pass Quantization elapsed time: 5582.69 ms
2021-10-15 21:05:37 [INFO] Pass QuantizedRNNConverter elapsed time: 36.06 ms
2021-10-15 21:05:39 [INFO] Pass StripUnusedNodesOptimizer elapsed time: 85.26 ms
2021-10-15 21:05:40 [INFO] Pass RemoveTrainingNodesOptimizer elapsed time: 34.33 ms
2021-10-15 21:05:40 [INFO] Pass FoldBatchNormNodesOptimizer elapsed time: 27.93 ms
2021-10-15 21:05:40 [INFO] Pass MetaOpOptimizer elapsed time: 15.89 ms
2021-10-15 21:05:47 [INFO] Pass PostCseOptimizer elapsed time: 4966.19 ms
2021-10-15 21:05:48 [INFO] |********Mixed Precision Statistics*******|
2021-10-15 21:05:48 [INFO] +---------------+---------+-------+-------+
2021-10-15 21:05:48 [INFO] |    Op Type    |  Total  |  INT8 |  FP32 |
2021-10-15 21:05:48 [INFO] +---------------+---------+-------+-------+
2021-10-15 21:05:48 [INFO] |     MatMul    |    63   |   62  |   1   |
2021-10-15 21:05:48 [INFO] |   QuantizeV2  |    38   |   38  |   0   |
2021-10-15 21:05:48 [INFO] |      Cast     |    1    |   0   |   1   |
2021-10-15 21:05:48 [INFO] +---------------+---------+-------+-------+
2021-10-15 21:05:48 [INFO] Pass quantize model elapsed time: 277215.1 ms
2021-10-15 21:05:48 [INFO] Tune 1 result is: [accuracy: 1.0000, duration (seconds): 0.0000], Best tune result is: [accuracy: 1.0000, duration (seconds): 0.0000]
2021-10-15 21:05:48 [INFO] Save tuning history to /localdisk/dmsuehir/frameworks.ai.models.intel-models/docs/notebooks/bert_classifier_fine_tuning/nc_workspace/2021-10-15_21-00-37/./history.snapshot.
2021-10-15 21:05:48 [INFO] Specified timeout or max trials is reached! Found a quantized model which meet accuracy goal. Exit.
2021-10-15 21:05:48 [INFO] Save deploy yaml to /localdisk/dmsuehir/frameworks.ai.models.intel-models/docs/notebooks/bert_classifier_fine_tuning/nc_workspace/2021-10-15_21-00-37/deploy.yaml
```

Toward the middle of that output it's saying `Tune 1 result is: [accuracy: 1.0000, duration (seconds): 0.0000], Best tune result is: [accuracy: 1.0000, duration (seconds): 0.0000]`. I'm wondering if the accuracy 1 and duration of 0 seconds means that something went wrong? I see the saved_model.pb in my output directory. Does this look like a successful run or is there anything wrong?

**Comment by hshen14** [comment]
cc @chensuyue

**Comment by chensuyue** [comment]
@GuoGuiRong Sorry for the late reply, may I know if the issue still there?

**Comment by asirvaiy** [comment]
Hi @chensuyue, I am seeing this same error for MaskRCNN_resnet50. I am providing publicly available mask_rcnn_coco weights(frozen .pb file) as input_model.

**Comment by asirvaiy** [comment]
https://github.com/matterport/Mask_RCNN/releases/tag/v2.0 Here is the model file in H5 format. I converted it to frozen form(pb). 
https://github.com/matterport/Mask_RCNN is the main repo for MaskRCNN TF model.

**Comment by chensuyue** [comment]
@zehao-intel pls check.

**Comment by zehao-intel** [comment]
Yes. I will track it.

**Comment by zehao-intel** [comment]
> Hi @chensuyue, I am seeing this same error for MaskRCNN_resnet50. I am providing publicly available mask_rcnn_coco weights(frozen .pb file) as input_model.

Hi @asirvaiy, the h5 file in the link you provided only contains weights. You need to use the main repo for MaskRCNN TF model to load this weight file to make it a complete model. Did you try this?
And if you have done so, could you provide the whole working flow regarding how did you generate the pb file?
Additionally, could you please paste the complete log for this error?

**Comment by asirvaiy** [comment]
> > Hi @chensuyue, I am seeing this same error for MaskRCNN_resnet50. I am providing publicly available mask_rcnn_coco weights(frozen .pb file) as input_model.
> 
> Hi @asirvaiy, the h5 file in the link you provided only contains weights. You need to use the main repo for MaskRCNN TF model to load this weight file to make it a complete model. Did you try this? And if you have done so, could you provide the whole working flow regarding how did you generate the pb file? Additionally, could you please paste the complete log for this error?

Hi @zehao-intel, I have used this https://github.com/Amith4504/Frozen-Graph-Inference-MaskRCNN to convert .h5 to .pb
I can also send you the .pb file.  Tried to use these instructions: https://github.com/intel/neural-compressor/tree/master/examples/tensorflow/object_detection/tensorflow_models/quantization/ptq

**Comment by zehao-intel** [comment]
Hi @asirvaiy.
Thanks for your reply!
I will check it ASAP.

**Comment by zehao-intel** [comment]
This "inputs len must equal with input_tensor" error occurs when the number of input data is not equal to the number of input tensors.
In this case, asirvairy's MaskRCNN pb file has three input tensors: image_image, input_image_meta, input_anchors
Hence, there should be three inputs to be feed into these tensors by constructing a feed_dict.

I have used correct input settings and preprocessing from the MaskRCNN repo to feed correct data. The model can be quantized with real data now.
