### ISSUE TITLE
`io.UnsupportedOperation: fileno` when running from Jupyter notebook

### ISSUE THREAD

**Issue by dmsuehir** [intel/neural-compressor#35]
I'm trying to run the neural compressor from a Jupyter notebook like:
```
quantizer.model = common.Model(os.path.join(output_dir, "frozen"))
quantizer.calib_dataloader = common.DataLoader(dataset, batch_size)
quantizer.eval_dataloader = common.DataLoader(dataset, batch_size)
quantizer.metric = common.Metric(metric_cls=Accuracy)

q_model = quantizer()
```
While running this, I'm getting following error:
```
2021-10-19 22:20:14 [INFO] Pass Quantization elapsed time: 5277.63 ms
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/adaptor/tf_utils/graph_converter.py", line 558, in quantize
    with CaptureOutputToFile(tmp_dump_file):
  File "/usr/local/lib/python3.8/dist-packages/neural_compressor/utils/utility.py", line 343, in __init__
    self.orig_stream_fileno = stream.fileno()
io.UnsupportedOperation: fileno
```
I think this is due to the way that the [notebook routes stdout and stderr output streams](https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Running%20Code.ipynb) to be seen in the notebook. The same script runs fine outside of the notebook (just using python).

Is there a way to workaround this to run the neural compressor quantization from a notebook?

**Comment by chensuyue** [comment]
No feedback over 2 weeks, closed at first.

**Comment by NeoZhangJianyu** [comment]
@dmsuehir 
I met same issue 2 years ago.
Recently, I find it's disappeared.
Maybe due to upgrade of 3rd part software.
I use pip install：
```
pip install --upgrade pip
pip install neural-compressor runipy notebook
```
Here is my software list, please refer:
neural-compressor        1.14.1
jupyter_client           7.4.2
jupyter-core             4.11.1
jupyter-server           1.21.0
jupyterlab-pygments      0.2.2
notebook                 6.5.1
notebook_shim            0.2.0

Thank you!
