### ISSUE TITLE
local variable 'tmp_model' referenced before assignment

### ISSUE THREAD

**Issue by zhentaocc** [intel/neural-compressor#39]
I am using version 1.8.0. And I got following error. Version 1.7.3 is fine.
```shell
Traceback (most recent call last):
  File "/home/zhentaoc/PycharmProjects/chronos-benchmark/forecaster/forecaster_tcn_altran_quant.py", line 148, in <module>
    quant_model = quantizer()
  File "/home/zhentaoc/anaconda3/envs/test/lib/python3.7/site-packages/neural_compressor/experimental/quantization.py", line 212, in __call__
    return super(Quantization, self).__call__()
  File "/home/zhentaoc/anaconda3/envs/test/lib/python3.7/site-packages/neural_compressor/experimental/component.py", line 208, in __call__
    self.pre_process()
  File "/home/zhentaoc/anaconda3/envs/test/lib/python3.7/site-packages/neural_compressor/experimental/quantization.py", line 144, in pre_process
    self.hooks)
  File "/home/zhentaoc/anaconda3/envs/test/lib/python3.7/site-packages/neural_compressor/strategy/basic.py", line 86, in __init__
    q_hooks)
  File "/home/zhentaoc/anaconda3/envs/test/lib/python3.7/site-packages/neural_compressor/strategy/strategy.py", line 189, in __init__
    self.capability = self.adaptor.query_fw_capability(model)
  File "/home/zhentaoc/anaconda3/envs/test/lib/python3.7/site-packages/neural_compressor/utils/utility.py", line 240, in fi
    res = func(*args, **kwargs)
  File "/home/zhentaoc/anaconda3/envs/test/lib/python3.7/site-packages/neural_compressor/adaptor/pytorch.py", line 806, in query_fw_capability
    tmp_model = self.fuse_fx_model(model)
  File "/home/zhentaoc/anaconda3/envs/test/lib/python3.7/site-packages/neural_compressor/adaptor/pytorch.py", line 844, in fuse_fx_model
    graph_module = GraphModule(tmp_model, tracer.trace(tmp_model))
UnboundLocalError: local variable 'tmp_model' referenced before assignment
```

**Comment by xin3he** [comment]
Yes, you're right. It's a logic issue happened in INC 1.8 when model cannot be deepcopy. Thank you for your report.

**Comment by xin3he** [comment]
We will fix this issue in next release v1.8.1, thanks

**Comment by ftian1** [comment]
pls try latest inc version to check if this issue solved

**Comment by zhentaocc** [comment]
> pls try latest inc version to check if this issue solved

It is. thx.
