### ISSUE TITLE
Wrong device for `distillation_for_quantization` example

### ISSUE THREAD

**Issue by philschmid** [intel/neural-compressor#415]
Hello, 

I was trying to run the [distillation_for_quantization](https://github.com/intel/neural-compressor/tree/v2.0/examples/pytorch/nlp/huggingface_models/text-classification/optimization_pipeline/distillation_for_quantization). But ran into several issues. 

First it seems that the script is not using the v2 API for the `compression_manager`, where you need to adjust the `train` method to go from `compression_manager.on_step_begin(step)` to `compression_manager.callbacks.on_step_begin(step)`. 

--- 

But the main error i am facing is `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument observer_on in method wrapper___fused_moving_avg_obs_fq_helper)`

```bash
/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/ao/quantization/fake_quantize.py:309: UserWarning: _aminmax is deprecated as of PyTorch 1.11 and will be removed in a future release. Use aminmax instead. This warning will only appear once per process. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525539683/work/aten/src/ATen/native/ReduceAllOps.cpp:45.)
  return torch.fused_moving_avg_obs_fake_quant(
Training:   0%|                                                                                                                                                   | 0/2104 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/deep-learning-pytorch-huggingface/optimization/scripts/run_glue_no_trainer.py", line 582, in <module>
    main()
  File "/home/ubuntu/deep-learning-pytorch-huggingface/optimization/scripts/run_glue_no_trainer.py", line 538, in main
    train(args, model, train_dataloader, lr_scheduler, compression_manager, optimizer, eval_dataloader,
  File "/home/ubuntu/deep-learning-pytorch-huggingface/optimization/scripts/run_glue_no_trainer.py", line 250, in train
    outputs = model(**batch)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/neural_compressor/model/torch_model.py", line 90, in forward
    return self._model(*args, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/fx/graph_module.py", line 658, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.0", line 38, in forward
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/fx/graph_module.py", line 658, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.224", line 7, in forward
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1201, in _call_impl
    result = hook(self, input)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/neural_compressor/adaptor/torch_utils/util.py", line 77, in input_scale_hook
    module.input_observer(input[0])
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/ao/quantization/fake_quantize.py", line 309, in forward
    return torch.fused_moving_avg_obs_fake_quant(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument observer_on in method wrapper___fused_moving_avg_obs_fq_helper)
```

I check the `batch`, `teacher` and `student` and all are placed on the same device (`cuda:0`) so it seems to be something internal, which i have no clue on.

## Versions

```
- `transformers` version: 4.25.1
- Platform: Linux-5.15.0-1026-aws-x86_64-with-glibc2.31
- Python version: 3.9.15
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.13.1 (True)
- Intel Neural Compressor: 2.0
```

**Comment by hshen14** [comment]
@philschmid Thanks for reporting the issue. We'll look into the issue and get back to you soon. CCed @PenghuiCheng @echarlaix

**Comment by PenghuiCheng** [comment]
@philschmid , Thanks for your report. and now the issue fixed by https://github.com/intel/neural-compressor/pull/445 and https://github.com/intel/neural-compressor/pull/418.

**Comment by PenghuiCheng** [comment]
PR merged
