### ISSUE TITLE
Missing classes in the coco label map

### ISSUE THREAD

**Issue by samir-souza** [intel/neural-compressor#44]
Please add the rest of the classes in the coco label map: https://github.com/intel/neural-compressor/blob/master/neural_compressor/experimental/metric/coco_label_map.py

The missing classes are breaking any code that tries to parse a coco dataset. 

You can use the following list as a reference.
https://gist.github.com/iitzco/3b2ee634a12f154be6e840308abfcab5

To reproduce the error, just try to compile a model using something like:
COCORaw:
          root: datasets/COCO
          img_dir: train2017
          anno_dir: annotations/instances_train2017.json

You'll get a KeyError exception with the first missing class the code finds you your annotation .json. If you edit coco_label_map.py and replace the dict by the one I pasted above, it solves the problem. 

Traceback (most recent call last):
  File "run.py", line 4, in <module>
    quantized_model = quantizer.fit()
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/neural_compressor/experimental/quantization.py", line 212, in __call__
    return super(Quantization, self).__call__()
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/neural_compressor/experimental/component.py", line 214, in __call__
    self.pre_process()
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/neural_compressor/experimental/quantization.py", line 120, in pre_process
    self._create_eval_dataloader(cfg)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/neural_compressor/experimental/quantization.py", line 83, in _create_eval_dataloader
    eval_dataloader_cfg)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/neural_compressor/utils/create_obj_from_config.py", line 96, in create_dataloader
    copy.deepcopy(dataloader_cfg['filter']),)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/neural_compressor/utils/create_obj_from_config.py", line 79, in create_dataset
    transform=preprocess, filter=filter)
  File "/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/neural_compressor/experimental/data/datasets/coco_dataset.py", line 186, in __init__
    labels.append(category_map[ann['category_id']].encode('utf8'))
KeyError: 12 <---- complaining about class 12

**Comment by mengniwang95** [comment]
Thank you for finding this issue, we will update it in next release.

**Comment by chensuyue** [comment]
Fixed in new release.
