### ISSUE TITLE
Knowledge Distillation Example Code is Broken

### ISSUE THREAD

**Issue by mhkwon924** [intel/neural-compressor#785]
Hello, I'm trying to use knowledge distillation in neural-compressor v2.1 for the first time. 
While running the example provided in this repository ([link](https://github.com/intel/neural-compressor/tree/master/examples/tensorflow/image_recognition/tensorflow_models/distillation)), I got the error msg below:

```Traceback (most recent call last):
  File "/home/mhkweun/proj/2023/neural-compressor/neural-compressor/examples/tensorflow/image_recognition/tensorflow_models/distillation/main.py", line 149, in <module>
    main()
  File "/home/mhkweun/proj/2023/neural-compressor/neural-compressor/examples/tensorflow/image_recognition/tensorflow_models/distillation/main.py", line 113, in main
    main_worker()
  File "/home/mhkweun/proj/2023/neural-compressor/neural-compressor/examples/tensorflow/image_recognition/tensorflow_models/distillation/main.py", line 136, in main_worker
    compression_manager = prepare_compression(model, conf)
  File "/home/mhkweun/anaconda3/envs/neural-compressor/lib/python3.9/site-packages/neural_compressor/training.py", line 324, in prepare_compression
    callbacks_list.append(DistillationCallbacks(confs, model=model))
  File "/home/mhkweun/anaconda3/envs/neural-compressor/lib/python3.9/site-packages/neural_compressor/compression/callbacks.py", line 602, in __init__
    self.model = model
  File "/home/mhkweun/anaconda3/envs/neural-compressor/lib/python3.9/site-packages/neural_compressor/compression/callbacks.py", line 218, in model
    if self.cfg.quantization.approach == "quant_aware_training":
AttributeError: 'NoneType' object has no attribute 'approach'
```

In my analysis, it seems to try to access quantization.approach variable from DistillationConfig class, which is not defined there. Moreover, there are several other issues similar to this, I encountered in running example.

Could you guide how I can fix this?

**Comment by zehao-intel** [comment]
Pull Request of fixing the issue has been raised.
