### ISSUE TITLE
Bug of Smooth quant alpha auto tuning

### ISSUE THREAD

**Issue by rnwang04** [intel/neural-compressor#834]
I have tried [this official example of Smooth quant alpha auto tuning](https://github.com/intel/neural-compressor/tree/master/examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant#smooth-quant-alpha-auto-tuning) and it will report below error：
```bash
2023-04-26 14:00:26 [INFO] Tune 1 result is: [Accuracy (int8|fp32): 0.6428|0.6517, Duration (seconds) (int8|fp32): 167.1900|404.7791], Best tune result is: n/a
2023-04-26 14:00:26 [INFO] |***********************Tune Result Statistics**********************|                                                            
2023-04-26 14:00:26 [INFO] +--------------------+-----------+---------------+------------------+                                                            
2023-04-26 14:00:26 [INFO] |     Info Type      |  Baseline | Tune 1 result | Best tune result |                                                            
2023-04-26 14:00:26 [INFO] +--------------------+-----------+---------------+------------------+                                                            2023-04-26 14:00:26 [INFO] |      Accuracy      |  0.6517   |    0.6428     |       n/a        |                                                            
2023-04-26 14:00:26 [INFO] | Duration (seconds) | 404.7791  |   167.1900    |       n/a        |                                                            
2023-04-26 14:00:26 [INFO] +--------------------+-----------+---------------+------------------+                                                            
2023-04-26 14:00:26 [INFO] Save tuning history to /root/ruonan/inc2-sq/neural-compressor/examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/nc_workspace/2023-04-26_13-48-57/./history.snapshot.                                                                        
2023-04-26 14:00:26 [INFO] Apply all recipes.
2023-04-26 14:00:26 [WARNING] Find evaluated tuning config, skip.
2023-04-26 14:00:26 [INFO] enter auto
2023-04-26 14:00:26 [ERROR] Unexpected exception KeyError('transformer.h.0.self_attention.query_key_value') happened during tuning.                         
Traceback (most recent call last):
  File "/opt/intel/oneapi/intelpython/latest/envs/ruonan-inc/lib/python3.9/site-packages/neural_compressor/quantization.py", line 132, in execute               self.strategy.traverse()
  File "/opt/intel/oneapi/intelpython/latest/envs/ruonan-inc/lib/python3.9/site-packages/neural_compressor/strategy/strategy.py", line 612, in traverse         self.model = self.algo_scheduler('pre_quantization')  File "/opt/intel/oneapi/intelpython/latest/envs/ruonan-inc/lib/python3.9/site-packages/neural_compressor/algorithm/algorithm.py", line 124, in __call__   
    self._q_model = algo(self._origin_model,
  File "/opt/intel/oneapi/intelpython/latest/envs/ruonan-inc/lib/python3.9/site-packages/neural_compressor/algorithm/smooth_quant.py", line 79, in __call__     q_model = adaptor.smooth_quant(origin_model, dataloader, calib_iter, self.tune_cfg, self.alpha,                                                         
  File "/opt/intel/oneapi/intelpython/latest/envs/ruonan-inc/lib/python3.9/site-packages/neural_compressor/adaptor/pytorch.py", line 1213, in smooth_quant  
    model._model = self.sq.transform(alpha=alpha, calib_iter=calib_iter, **args)                                                                              File "/opt/intel/oneapi/intelpython/latest/envs/ruonan-inc/lib/python3.9/site-packages/neural_compressor/adaptor/torch_utils/smooth_quant.py", line 584, in transform
    self.auto_tune_alpha(input_maxes)
  File "/opt/intel/oneapi/intelpython/latest/envs/ruonan-inc/lib/python3.9/site-packages/neural_compressor/adaptor/torch_utils/smooth_quant.py", line 493, in auto_tune_alpha
    input_of_op, output_of_op = self.input_values[layer_key], self.output_values[layer_key]                                                                 KeyError: 'transformer.h.0.self_attention.query_key_value'
2023-04-26 14:00:26 [ERROR] Specified timeout or max trials is reached! Not found any quantized model which meet accuracy goal. Exit.                       
Traceback (most recent call last):
  File "/root/ruonan/inc2-sq/neural-compressor/examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/eval_lambada.py", line 163, in <module>
    q_model.save(f"{save_model_name}")
AttributeError: 'NoneType' object has no attribute 'save'
```

By the way I can reproduce this bug on other LLM.

**Comment by xin3he** [comment]
Hi, @rnwang04 , we have resolved this issue in our master branch.
You can install `neural_compressor` with our master branch, thanks.

**Comment by rnwang04** [comment]
@xin3he  Thanks a lot! I will have a try!
Another question here: of course the  quantized model has faster forward function, however, for most LLM model, we will directly call the `generate` function.
Inside the `generate` function, we will have different forms of input like `model(input_ids)` and `model(input_ids, past_key_value=past_key_value`.
However, as the model in the sq example is optimized by ipex backend, the returned model has been called `jit.trace` with only one input. So it no longer accept past_key_value parameters which I think is a big problem for llm.
I wonder the `jit.trace` is called by inc or by ipex? 
Can inc directly return models that have not yet been traced? Or expose corresponding parameters to provide greater flexibility to users? Or do you have any existing solutions to this problem?

**Comment by rnwang04** [comment]
By the way, does smooth quant alpha auto tuning only work for ipex backend？

**Comment by xin3he** [comment]
SmoothQuant only works in IPEX backend, and jit tracing is required by IPEX.
You can expect that IPEX2.1 (WIP) will resolve the input issue and we will public some examples for LLM text generation later.

**Comment by attafosu** [comment]
> @xin3he Thanks a lot! I will have a try! Another question here: of course the quantized model has faster forward function, however, for most LLM model, we will directly call the `generate` function. Inside the `generate` function, we will have different forms of input like `model(input_ids)` and `model(input_ids, past_key_value=past_key_value`. However, as the model in the sq example is optimized by ipex backend, the returned model has been called `jit.trace` with only one input. So it no longer accept past_key_value parameters which I think is a big problem for llm. I wonder the `jit.trace` is called by inc or by ipex? Can inc directly return models that have not yet been traced? Or expose corresponding parameters to provide greater flexibility to users? Or do you have any existing solutions to this problem?

This is an important point for LLMs. The quantized model doesn't give the option to pass some key parameters to during inference. @xin3he any thoughts on this.
